services:
  - type: web
    name: bankmanager-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    buildCommand: "docker build -t bankmanager ."
    startCommand: "./start.sh"
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: array
      - key: L5_SWAGGER_GENERATE_ALWAYS
        value: false
      - key: DB_CONNECTION
        value: pgsql
      # Variables Railway
      - key: DB_HOST
        value: containers-us-west-1.railway.app
      - key: DB_PORT
        value: 1234
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: hUpXRElCfFBvUcqOczDStyBOYfVoferR